apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: ${NAMESPACE}-azure-${CLUSTERNAME}
  namespace: ${NAMESPACE}
spec:
  template: demo-azure-standalone-cp-0.0.2
  credential: azure-cluster-identity-cred
  config:
    controlPlaneNumber: 1
    workersNumber: 2
    location: "westus"
    subscriptionID: ${AZURE_SUBSCRIPTION_ID} 
    controlPlane:
      vmSize: Standard_A4_v2
    worker:
      vmSize: Standard_A4_v2
    clusterIdentity:
      name: azure-cluster-identity
      namespace: k0rdent
