---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: azure-cluster-identity
  namespace: ${TESTING_NAMESPACE}
spec:
  allowedNamespaces: {}
  clientID: ${AZURE_SP_APP_ID}
  clientSecret:
    name: azure-cluster-identity-secret
    namespace: ${TESTING_NAMESPACE}
  tenantID: ${AZURE_SP_TENANT_ID}
  type: ServicePrincipal
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-cluster-identity-secret
  namespace: ${TESTING_NAMESPACE}
stringData:
  clientSecret: ${AZURE_SP_PASSWORD}
type: Opaque
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: azure-cluster-identity-cred
  namespace: ${TESTING_NAMESPACE}
spec:
  description: Azure credentials
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: azure-cluster-identity
    namespace: ${TESTING_NAMESPACE}
